version: '3'
services:
  myapp-main:
    image: docker_qap:latest
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/docker_qap
      - spring.datasource.password=Keyin202!
      - spring.datasource.username=root