#version: '3'
#services:
#  myapp-main:
#    image: docker_qap:latest
#    ports:
#      - "8080:8080"
#    environment:
#      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/devops_docker_qap
#      - spring.datasource.password=rootMaster1alskdjbguiyasdghfi8sghdf
#      - spring.datasource.username=root
version: '3'
services:
  myapp-main:
    image: docker_qap:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/devops_docker_qap
      #- spring.datasource.url=jdbc:mysql://s4-fall-2022.ce2vcezehro2.us-east-1.rds.amazonaws.com/fall_2022
      - spring.datasource.password=rootMaster1alskdjbguiyasdghfi8sghdf
      - spring.datasource.username=root